### PR TITLE
fixed it missing a lot of addons and caching

### PR DESCRIPTION
**Pull request by storm37000**

### CODE REVIEW

**Comment by MDFL64** [comment]
So you've added one resource file type and removed the map inclusion?

Okay with the former, not sure about the latter. I'm still not convinced to this day that Gmod handles map workshop downloads correctly.

**Comment by storm37000** [comment]
i run a server and it always sends the map through workshop to the player.

**Comment by ThatLing** [comment]
Loads of servers use workshop for maps. It fucking sucks though since you can't join the server without enabling workshop downloads.

**Comment by storm37000** [comment]
isnt that what this addon is for? its useless without enabling workshop downloads.

**Review by tintinmaster — APPROVED** [review]

**Comment by MDFL64** [comment]
Hey, let me know if you want push access to this repo and workshop page. I have some misgivings about map downloads and caching, but I lost interest in Gmod for the most part a long time ago. Better to have someone who's actually interested in maintaining the damn thing.

**Comment by storm37000** [comment]
that sounds good, im fine with maintaining it, you may want to remove the outdated version off the workshop to greatly reduce confusion.  I can add a convar config option serverside to re enable it giving all maps to clients.

**Comment by MDFL64** [comment]
Alright. I've given you write access to the repo. It looks like Steam only lets you add friends as contributors, so I've sent you a friend request.

**Comment by storm37000** [comment]
ok, i accepted your fr.

**Comment by MDFL64** [comment]
Alright. Sorry for the slowness on my end. I've added you as a contributor on the workshop.

**Pull request merged**
