### PR TITLE
Fix material packs not being auto-added

### PR DESCRIPTION
**Pull request by wyozi**
I assume logic for not including vtf/vmt is map thumbnails or something. This adds material packs if there are materials in materials folder.

For reference origin/master as of now does not auto-add eg. http://steamcommunity.com/workshop/filedetails/?id=538347004

### CODE REVIEW

**Comment by wyozi** [comment]
Also did not test PR yet. Will do very soon.

**Comment by wyozi** [comment]
This PR was a mistake. Bunch of map addons still get added in.

I feel like best way to do this would be to instead of returning a boolean value return a table containing all filetypes found in an addon. Then postprocess step could do filtering better. I'll look into this later.

**Comment by wyozi** [comment]
I changed the whole inclusion logic quite a bit in the latest commit. Addons that contained .bsp files (other than current map) but also had .mdl files were included, which I think is invalid logic, because an addon that contains a map file is presumably a map addon (could be a problem with TTT servers having bunch of map addons some of which may contain models).

The inclusion algorithm is now something like this:
- If contains .bsp that is the current map, include
- If contains a resource_extension and no map file, include
- Otherwise exclude

**Comment by MDFL64** [comment]
Sorry for the delay. I've been... uh... downloading lua from the steam workshop. All of it.

Seems like pretty fair logic to me. I don't have any kind of server to test this with, so I'll assume it's okay. Maybe I should try making some kind of lazy version that tries to load and mount addons on demand...

**Comment by MDFL64** [comment]
So unless my friend's server has some other nonsense on it, gmod seems to handle workshop maps itself now. Maybe.

**Comment by bmwalters** [comment]
it always has

**Pull request merged**
